[workspace]
members = [".", "rswarm_examples"]

[package]
name = "rswarm"
version = "0.1.5"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A Rust implementation of the Swarm framework"

[dependencies]
actix-web = "4.9.0"
anyhow = "1.0.89"
async-stream = "0.3.6"
chrono = "0.4.38"
dotenv = { version = "0.15.0", features = ["clap", "cli"] }
futures = "0.3.31"
futures-util = "0.3.31"
lazy_static = "1.5.0"
mcp_rs = "0.1.0"
openai-mock = "0.1.0"
openrouter_api = "0.1.2"
quick-xml = { version = "0.36.2", features = ["serde", "serialize"] }
regex = "1.11.0"
reqwest = { version = "0.12.9", features = [
    "json",
    "blocking",
    "stream",
    "rustls-tls",
] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
thiserror = "2.0.3"
tokio = { version = "1.40.0", features = ["full", "test-util", "rt", "macros"] }
tracing = "0.1.40"
url = "2.5.3"
wiremock = "0.6"

[dev-dependencies]
# Remove or comment out mockito
# mockito = "1.6.1"

# Add wiremock
wiremock = "0.6"
tokio = { version = "1.40.0", features = ["full", "test-util", "rt", "macros"] }
serde_json = "1.0.128"
